name: Lambda

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build_and_deploy:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - uses: dtolnay/rust-toolchain@stable
    - run: rustup target add aarch64-unknown-linux-gnu
    - uses: korandoru/setup-zig@v1
      with:
        zig-version: 0.13.0 # released versions or master
    - uses: zerj9/setup-cargo-lambda@v0.1.0
    - run: cargo lambda build --arm64 -r
    - name: Deploy
      run: |
        cargo lambda deploy get_info --iam-role ${{ secrets.LAMBDA_IAM }} --region us-east-1
        cargo lambda deploy stop_streaming --iam-role ${{ secrets.LAMBDA_IAM }} --region us-east-1
